# Generated by Django 2.1.7 on 2019-08-13 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_delete_userregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default='1')),
                ('difficulty', models.FloatField(default='1')),
                ('security', models.FloatField(default='1')),
                ('trekking_type', multiselectfield.db.fields.MultiSelectField(choices=[('Cycling', 'Cycling'), ('Walking', 'Walking'), ('Biking', 'Biking'), ('Peak Climbing', 'Peak Climbing'), ('Others', 'Others')], default='Walking', max_length=43)),
                ('destinaton_type', multiselectfield.db.fields.MultiSelectField(choices=[('Adventure', 'Adventure'), ('Pilgrims', 'Pilgrims'), ('Waterbody', 'Waterbody'), ('Himalayas', 'Himalayas'), ('Nature Seeing', 'Nature Seeing'), ('Others', 'Others')], default='Adventure', max_length=59)),
                ('accomodation_type', multiselectfield.db.fields.MultiSelectField(choices=[('Hotel', 'Hotel'), ('Teahouse', 'Teahouse'), ('Motel', 'Motel'), ('Tent', 'Tent'), ('Homestay', 'Homestay')], default='Hotel', max_length=34)),
                ('latitude', models.FloatField(default='1')),
                ('longitude', models.FloatField(default='1')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
