# Generated by Django 2.1.7 on 2019-08-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190816_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='latitude',
            field=models.FloatField(blank=True, default='27.6817', null=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='longitude',
            field=models.FloatField(blank=True, default='85.3170', null=True),
        ),
    ]
