# Generated by Django 2.1.7 on 2019-08-16 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_uservisited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservisited',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='uservisited',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserVisited',
        ),
    ]
